apiVersion: v1
kind: Service
metadata:
  name: kata-app-service
  namespace: kata-app
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30007 # Port exposed on the nodes
  selector:
    app: kata-app